version: '3.1'

services:
  mongo-file-db:
    image: mongo
    container_name: mongo-file
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1q2w3e4r5t
      MONGO_DB_DEV_USERNAME: developer
      MONGO_DB_DEV_PASSWORD: 1q2w3e4r5t
      MONGO_DB_DATABASE: free-music
      MONGO_DB_COLLECTION: file
    ports:
      - "2717:27017"
    volumes:
      - ../mongodb-data:/data/db

  file-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-manager
    ports:
      - "8001:8080"
    depends_on:
      - mongo-file-db
    volumes:
      - ./configs:/configs
volumes:
  mongodb-data: